auth/urls.py
from django.urls import path
from auth import views
urlpatterns=[
    path('login',views.Login.as_view()),
    path('logout',views.logout.as_view()),
    path('signup',views.signup.as_view())
]

friends/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/' ,include('auth.urls')),
   
    path('',include('social.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from social import views
urlpatterns=[
    path('home/',views.Home.as_view()),
    path('post/',views.post.as_view()),
    path('myfriends/',views.myfriends.as_view()),
    path('post/<int:pk>/like',views.PostLike.as_view()),
    path('',views.wall.as_view())
]

social/models.py
from django.db import models
from django.contrib.auth.models import User
class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now=True)
    content=models.TextField()
    image=models.ImageField(blank=True)
    def __str__(self):
        return self.content[:50]
    

class frnds(models.Model):
    person1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='person1')
    person2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='person2')

class Like(models.Model):
    post=models.ForeignKey('Post',on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

class Comment(models.Model):
    post=models.ForeignKey('Post',on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.CharField(max_length=1000)

social/forms.py
from django import forms
from social  import models
class PostForm(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=['content','image']

social/views.py
from django.shortcuts import render,redirect
from social import models
from django.db.models import Q
from django.views import View
from social  import forms
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib.auth.models import User
# Create your views here.
class wall(LoginRequiredMixin,ListView):
    
    context_object_name='posts'
    template_name='social/wall.html'
    login_url='auth/login'
    def get_queryset(self):
        friendid=[friend.person2.id for friend in models.frnds.objects.filter(person1=self.request.user)]
        friendid= friendid + [friend.person1.id for friend in models.frnds.objects.filter(person2=self.request.user)]
        return models.Post.objects.filter(user__in=friendid).order_by('-created_at')
        
class Home(LoginRequiredMixin,ListView):
    context_object_name='posts'
    template_name='social/home.html'
    login_url='auth/login'
    def get_queryset(self):
        return models.Post.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        data=super().get_context_data(*args,**kwargs)
        data['post_form']=forms.PostForm
        return data
class post(View):
    def post(self,request):
        form=forms.PostForm(request.POST,request.FILES)
        if form.is_valid():
            newpost=form.save(commit=False)
            newpost.user=request.user
            newpost.save()
            return redirect('/home')

class PostLike(View):
    model=models.Post
    def post(self,request,pk):
        newpost=self.model.objects.get(pk=pk)
        print(1)
        models.Like.objects.create(post=newpost,user=request.user)
        return HttpResponse(code=204)

class myfriends(ListView):
    context_object_name='friends'
    template_name='social/myfriends.html'
    
    def get_queryset(self):
        friendid=[friend.person2.id for friend in models.frnds.objects.filter(person1=self.request.user)]
        friendid= friendid + [friend.person1.id for friend in models.frnds.objects.filter(person2=self.request.user)]
        return User.objects.filter(id__in=friendid)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>friends</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    {% block head %}{% endblock %}
</head>
<body>
    <nav style="margin-bottom: 1.5rem;">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Logo</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              {% if user.is_authenticated %}
            <li><a href="/home">Hello, {{user.first_name}} {{user.last_name}}</a></li>
            <li><a href="/myfriends">Friends</a></li>
            <li><a href="/auth/logout">logout</a></li>
            {% else %}
            <li><a href="/auth/login">login</a></li>
            {% endif %}
          </ul>
        </div>
    </nav>
    {% block content %} {% endblock %}
    {% block footer %} {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="\static\social\social.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.modal');
        var instances = M.Modal.init(elems, {});
      });
    </script>
    
    
            
</body>
</html>

templates/components/post.html
<div class="card">
    <div class="card-image">
        {% if post.image %}
      <img src="/media/{{post.image}}" style="width:70%">
      

      {% endif %}
    </div>
    <div class="card-content">
        <h5>{{post.user.first_name}}</h5>
       
      <p>{{post.content}}</p>
      <p>  {{post.created_at}}</p>
    </div>
    <div class="card-action">
        <a href="#" onclick="likepost({{post.id}})" >{{post.like_set.count}} Likes</a>
        <a class="modal-trigger" href="#{{post.id}}">{{post.comment_set.count}} Comments</a>
      </div>

  </div>
  <div id="{{post.id}}" class="modal">
    <div class="modal-content">
      <h5>comments</h5>
      <ul>
      {% for comment in post.comment_set.all %}
        
      <li>{{comment.user.first_name}}-{{comment.content}}</li>
      {% endfor %}
      </ul>
    </div>
    <div class="modal-footer">
   
    </div>
  </div>
          
 
 
 

templates/social/home.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
<form action="/post/" method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{post_form}}  
    <button  class="waves-effect waves-light btn" type="submit">post</button>
{% for post in posts %}
<div class="row">

<div class="col s8 offset-s2">
{% include 'components/post.html' %}


</div>
</div>

{% endfor %}
</div>
{% endblock %}

templates/social/myfriends.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    
{% for f in friends %}
<div class="row">

{{f}}



</div>

{% endfor %}
</div>
{% endblock %}%}

templates/social/wall.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    
{% for post in posts %}
<div class="row">

<div class="col s8 offset-s2">
{% include 'components/post.html' %}


</div>
</div>

{% endfor %}
</div>
{% endblock %}